"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class HederaKey(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ED25519_FIELD_NUMBER: builtins.int
    ed25519: builtins.bytes
    def __init__(
        self,
        *,
        ed25519: builtins.bytes = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["ed25519", b"ed25519", "key", b"key"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["ed25519", b"ed25519", "key", b"key"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["key", b"key"]) -> typing_extensions.Literal["ed25519"] | None: ...

global___HederaKey = HederaKey

@typing_extensions.final
class HederaShardID(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SHARDNUM_FIELD_NUMBER: builtins.int
    shardNum: builtins.int
    def __init__(
        self,
        *,
        shardNum: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["shardNum", b"shardNum"]) -> None: ...

global___HederaShardID = HederaShardID

@typing_extensions.final
class HederaRealmID(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SHARDNUM_FIELD_NUMBER: builtins.int
    REALMNUM_FIELD_NUMBER: builtins.int
    shardNum: builtins.int
    realmNum: builtins.int
    def __init__(
        self,
        *,
        shardNum: builtins.int = ...,
        realmNum: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["realmNum", b"realmNum", "shardNum", b"shardNum"]) -> None: ...

global___HederaRealmID = HederaRealmID

@typing_extensions.final
class HederaAccountID(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SHARDNUM_FIELD_NUMBER: builtins.int
    REALMNUM_FIELD_NUMBER: builtins.int
    ACCOUNTNUM_FIELD_NUMBER: builtins.int
    shardNum: builtins.int
    realmNum: builtins.int
    accountNum: builtins.int
    def __init__(
        self,
        *,
        shardNum: builtins.int = ...,
        realmNum: builtins.int = ...,
        accountNum: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["accountNum", b"accountNum", "realmNum", b"realmNum", "shardNum", b"shardNum"]) -> None: ...

global___HederaAccountID = HederaAccountID

@typing_extensions.final
class HederaTokenID(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SHARDNUM_FIELD_NUMBER: builtins.int
    REALMNUM_FIELD_NUMBER: builtins.int
    TOKENNUM_FIELD_NUMBER: builtins.int
    shardNum: builtins.int
    realmNum: builtins.int
    tokenNum: builtins.int
    def __init__(
        self,
        *,
        shardNum: builtins.int = ...,
        realmNum: builtins.int = ...,
        tokenNum: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["realmNum", b"realmNum", "shardNum", b"shardNum", "tokenNum", b"tokenNum"]) -> None: ...

global___HederaTokenID = HederaTokenID

@typing_extensions.final
class HederaTimestamp(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SECONDS_FIELD_NUMBER: builtins.int
    NANOS_FIELD_NUMBER: builtins.int
    seconds: builtins.int
    nanos: builtins.int
    def __init__(
        self,
        *,
        seconds: builtins.int = ...,
        nanos: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["nanos", b"nanos", "seconds", b"seconds"]) -> None: ...

global___HederaTimestamp = HederaTimestamp

@typing_extensions.final
class HederaDuration(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SECONDS_FIELD_NUMBER: builtins.int
    seconds: builtins.int
    def __init__(
        self,
        *,
        seconds: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["seconds", b"seconds"]) -> None: ...

global___HederaDuration = HederaDuration

@typing_extensions.final
class HederaTransactionID(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ACCOUNTID_FIELD_NUMBER: builtins.int
    @property
    def accountID(self) -> global___HederaAccountID: ...
    def __init__(
        self,
        *,
        accountID: global___HederaAccountID | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["accountID", b"accountID"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["accountID", b"accountID"]) -> None: ...

global___HederaTransactionID = HederaTransactionID
