/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.5 */

#include "proto/basic_types.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(Hedera_ShardID, Hedera_ShardID, AUTO)


PB_BIND(Hedera_RealmID, Hedera_RealmID, AUTO)


PB_BIND(Hedera_AccountID, Hedera_AccountID, AUTO)


PB_BIND(Hedera_FileID, Hedera_FileID, AUTO)


PB_BIND(Hedera_ContractID, Hedera_ContractID, AUTO)


PB_BIND(Hedera_TransactionID, Hedera_TransactionID, AUTO)


PB_BIND(Hedera_AccountAmount, Hedera_AccountAmount, AUTO)


PB_BIND(Hedera_TransferList, Hedera_TransferList, AUTO)


PB_BIND(Hedera_NftTransfer, Hedera_NftTransfer, AUTO)


PB_BIND(Hedera_TokenTransferList, Hedera_TokenTransferList, 2)


PB_BIND(Hedera_Fraction, Hedera_Fraction, AUTO)


PB_BIND(Hedera_TokenID, Hedera_TokenID, AUTO)


PB_BIND(Hedera_Key, Hedera_Key, AUTO)


PB_BIND(Hedera_ThresholdKey, Hedera_ThresholdKey, AUTO)


PB_BIND(Hedera_KeyList, Hedera_KeyList, AUTO)


PB_BIND(Hedera_TokenBalance, Hedera_TokenBalance, AUTO)


PB_BIND(Hedera_TokenBalances, Hedera_TokenBalances, AUTO)


PB_BIND(Hedera_TokenAssociation, Hedera_TokenAssociation, AUTO)


PB_BIND(Hedera_StakingInfo, Hedera_StakingInfo, AUTO)



