/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.5 */

#include "proto/crypto_update.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(Hedera_CryptoUpdateTransactionBody, Hedera_CryptoUpdateTransactionBody, 2)



