/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.5 */

#ifndef PB_HEDERA_PROTO_DURATION_PB_H_INCLUDED
#define PB_HEDERA_PROTO_DURATION_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
/* *
 A length of time in seconds. */
typedef struct _Hedera_Duration { 
    /* *
 The number of seconds */
    int64_t seconds; 
} Hedera_Duration;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define Hedera_Duration_init_default             {0}
#define Hedera_Duration_init_zero                {0}

/* Field tags (for use in manual encoding/decoding) */
#define Hedera_Duration_seconds_tag              1

/* Struct field encoding specification for nanopb */
#define Hedera_Duration_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT64,    seconds,           1)
#define Hedera_Duration_CALLBACK NULL
#define Hedera_Duration_DEFAULT NULL

extern const pb_msgdesc_t Hedera_Duration_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define Hedera_Duration_fields &Hedera_Duration_msg

/* Maximum encoded size of messages (where known) */
#define Hedera_Duration_size                     11

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
