/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.5 */

#ifndef PB_HEDERA_PROTO_TIMESTAMP_PB_H_INCLUDED
#define PB_HEDERA_PROTO_TIMESTAMP_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
/* *
 An exact date and time. This is the same data structure as the protobuf
 Timestamp.proto (see the comments in
 https://github.com/google/protobuf
 /blob/master/src/google/protobuf/timestamp.proto) */
typedef struct _Hedera_Timestamp { 
    /* *
 Number of complete seconds since the start of the epoch */
    int64_t seconds; 
    /* *
 Number of nanoseconds since the start of the last second */
    int32_t nanos; 
} Hedera_Timestamp;

/* *
 An exact date and time,  with a resolution of one second (no nanoseconds). */
typedef struct _Hedera_TimestampSeconds { 
    /* *
 Number of complete seconds since the start of the epoch */
    int64_t seconds; 
} Hedera_TimestampSeconds;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define Hedera_Timestamp_init_default            {0, 0}
#define Hedera_TimestampSeconds_init_default     {0}
#define Hedera_Timestamp_init_zero               {0, 0}
#define Hedera_TimestampSeconds_init_zero        {0}

/* Field tags (for use in manual encoding/decoding) */
#define Hedera_Timestamp_seconds_tag             1
#define Hedera_Timestamp_nanos_tag               2
#define Hedera_TimestampSeconds_seconds_tag      1

/* Struct field encoding specification for nanopb */
#define Hedera_Timestamp_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT64,    seconds,           1) \
X(a, STATIC,   SINGULAR, INT32,    nanos,             2)
#define Hedera_Timestamp_CALLBACK NULL
#define Hedera_Timestamp_DEFAULT NULL

#define Hedera_TimestampSeconds_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT64,    seconds,           1)
#define Hedera_TimestampSeconds_CALLBACK NULL
#define Hedera_TimestampSeconds_DEFAULT NULL

extern const pb_msgdesc_t Hedera_Timestamp_msg;
extern const pb_msgdesc_t Hedera_TimestampSeconds_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define Hedera_Timestamp_fields &Hedera_Timestamp_msg
#define Hedera_TimestampSeconds_fields &Hedera_TimestampSeconds_msg

/* Maximum encoded size of messages (where known) */
#define Hedera_TimestampSeconds_size             11
#define Hedera_Timestamp_size                    22

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
