"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import proto.BasicTypes_pb2
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class HederaTokenAssociateTransactionBody(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ACCOUNT_FIELD_NUMBER: builtins.int
    TOKENS_FIELD_NUMBER: builtins.int
    @property
    def account(self) -> proto.BasicTypes_pb2.HederaAccountID: ...
    @property
    def tokens(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[proto.BasicTypes_pb2.HederaTokenID]: ...
    def __init__(
        self,
        *,
        account: proto.BasicTypes_pb2.HederaAccountID | None = ...,
        tokens: collections.abc.Iterable[proto.BasicTypes_pb2.HederaTokenID] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["account", b"account"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["account", b"account", "tokens", b"tokens"]) -> None: ...

global___HederaTokenAssociateTransactionBody = HederaTokenAssociateTransactionBody
