/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.5 */

#ifndef PB_HEDERA_PROTO_TOKEN_DISSOCIATE_PB_H_INCLUDED
#define PB_HEDERA_PROTO_TOKEN_DISSOCIATE_PB_H_INCLUDED
#include <pb.h>
#include "proto/basic_types.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
/* *
 Dissociates the provided account with the provided tokens. Must be signed by
 the provided Account's key. If the provided account is not found, the
 transaction will resolve to INVALID_ACCOUNT_ID. If the provided account has
 been deleted, the transaction will resolve to ACCOUNT_DELETED. If any of the
 provided tokens is not found, the transaction will resolve to
 INVALID_TOKEN_REF. If any of the provided tokens has been deleted, the
 transaction will resolve to TOKEN_WAS_DELETED. If an association between the
 provided account and any of the tokens does not exist, the transaction will
 resolve to TOKEN_NOT_ASSOCIATED_TO_ACCOUNT. If a token has not been deleted
 and has not expired, and the user has a nonzero balance, the transaction will
 resolve to TRANSACTION_REQUIRES_ZERO_TOKEN_BALANCES. If a <b>fungible
 token</b> has expired, the user can disassociate even if their token balance
 is not zero. If a <b>non fungible token</b> has expired, the user can
 <b>not</b> disassociate if their token balance is not zero. The transaction
 will resolve to TRANSACTION_REQUIRED_ZERO_TOKEN_BALANCES. On success,
 associations between the provided account and tokens are removed. */
typedef struct _Hedera_TokenDissociateTransactionBody { 
    /* *
 The account to be dissociated with the provided tokens */
    bool has_account;
    Hedera_AccountID account; 
    /* *
 The tokens to be dissociated with the provided account
 Limited to 1 here */
    pb_size_t tokens_count;
    Hedera_TokenID tokens[1]; 
} Hedera_TokenDissociateTransactionBody;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define Hedera_TokenDissociateTransactionBody_init_default {false, Hedera_AccountID_init_default, 0, {Hedera_TokenID_init_default}}
#define Hedera_TokenDissociateTransactionBody_init_zero {false, Hedera_AccountID_init_zero, 0, {Hedera_TokenID_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define Hedera_TokenDissociateTransactionBody_account_tag 1
#define Hedera_TokenDissociateTransactionBody_tokens_tag 2

/* Struct field encoding specification for nanopb */
#define Hedera_TokenDissociateTransactionBody_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  account,           1) \
X(a, STATIC,   REPEATED, MESSAGE,  tokens,            2)
#define Hedera_TokenDissociateTransactionBody_CALLBACK NULL
#define Hedera_TokenDissociateTransactionBody_DEFAULT NULL
#define Hedera_TokenDissociateTransactionBody_account_MSGTYPE Hedera_AccountID
#define Hedera_TokenDissociateTransactionBody_tokens_MSGTYPE Hedera_TokenID

extern const pb_msgdesc_t Hedera_TokenDissociateTransactionBody_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define Hedera_TokenDissociateTransactionBody_fields &Hedera_TokenDissociateTransactionBody_msg

/* Maximum encoded size of messages (where known) */
#define Hedera_TokenDissociateTransactionBody_size 94

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
