"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import proto.BasicTypes_pb2
import proto.Wrappers_pb2
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class HederaAccountAmount(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ACCOUNTID_FIELD_NUMBER: builtins.int
    AMOUNT_FIELD_NUMBER: builtins.int
    @property
    def accountID(self) -> proto.BasicTypes_pb2.HederaAccountID: ...
    amount: builtins.int
    def __init__(
        self,
        *,
        accountID: proto.BasicTypes_pb2.HederaAccountID | None = ...,
        amount: builtins.int = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["accountID", b"accountID"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["accountID", b"accountID", "amount", b"amount"]) -> None: ...

global___HederaAccountAmount = HederaAccountAmount

@typing_extensions.final
class HederaTransferList(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ACCOUNTAMOUNTS_FIELD_NUMBER: builtins.int
    @property
    def accountAmounts(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___HederaAccountAmount]: ...
    def __init__(
        self,
        *,
        accountAmounts: collections.abc.Iterable[global___HederaAccountAmount] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["accountAmounts", b"accountAmounts"]) -> None: ...

global___HederaTransferList = HederaTransferList

@typing_extensions.final
class HederaTokenTransferList(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TOKEN_FIELD_NUMBER: builtins.int
    TRANSFERS_FIELD_NUMBER: builtins.int
    EXPECTED_DECIMALS_FIELD_NUMBER: builtins.int
    @property
    def token(self) -> proto.BasicTypes_pb2.HederaTokenID: ...
    @property
    def transfers(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___HederaAccountAmount]: ...
    @property
    def expected_decimals(self) -> proto.Wrappers_pb2.UInt32Value:
        """*
        If present, the number of decimals this fungible token type is expected to
        have. The transfer will fail with UNEXPECTED_TOKEN_DECIMALS if the actual
        decimals differ.
        """
    def __init__(
        self,
        *,
        token: proto.BasicTypes_pb2.HederaTokenID | None = ...,
        transfers: collections.abc.Iterable[global___HederaAccountAmount] | None = ...,
        expected_decimals: proto.Wrappers_pb2.UInt32Value | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["expected_decimals", b"expected_decimals", "token", b"token"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["expected_decimals", b"expected_decimals", "token", b"token", "transfers", b"transfers"]) -> None: ...

global___HederaTokenTransferList = HederaTokenTransferList

@typing_extensions.final
class HederaCryptoTransferTransactionBody(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TRANSFERS_FIELD_NUMBER: builtins.int
    TOKENTRANSFERS_FIELD_NUMBER: builtins.int
    @property
    def transfers(self) -> global___HederaTransferList: ...
    @property
    def tokenTransfers(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___HederaTokenTransferList]: ...
    def __init__(
        self,
        *,
        transfers: global___HederaTransferList | None = ...,
        tokenTransfers: collections.abc.Iterable[global___HederaTokenTransferList] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["transfers", b"transfers"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["tokenTransfers", b"tokenTransfers", "transfers", b"transfers"]) -> None: ...

global___HederaCryptoTransferTransactionBody = HederaCryptoTransferTransactionBody
