"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import proto.BasicTypes_pb2
import proto.CryptoCreate_pb2
import proto.TokenAssociate_pb2
import proto.TokenBurn_pb2
import proto.TokenMint_pb2
import proto.Transfer_pb2
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class HederaTransactionBody(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TRANSACTIONID_FIELD_NUMBER: builtins.int
    TRANSACTIONFEE_FIELD_NUMBER: builtins.int
    MEMO_FIELD_NUMBER: builtins.int
    CRYPTOCREATEACCOUNT_FIELD_NUMBER: builtins.int
    CRYPTOTRANSFER_FIELD_NUMBER: builtins.int
    TOKENASSOCIATE_FIELD_NUMBER: builtins.int
    TOKENMINT_FIELD_NUMBER: builtins.int
    TOKENBURN_FIELD_NUMBER: builtins.int
    @property
    def transactionID(self) -> proto.BasicTypes_pb2.HederaTransactionID: ...
    transactionFee: builtins.int
    memo: builtins.str
    @property
    def cryptoCreateAccount(self) -> proto.CryptoCreate_pb2.HederaCryptoCreateTransactionBody: ...
    @property
    def cryptoTransfer(self) -> proto.Transfer_pb2.HederaCryptoTransferTransactionBody: ...
    @property
    def tokenAssociate(self) -> proto.TokenAssociate_pb2.HederaTokenAssociateTransactionBody: ...
    @property
    def tokenMint(self) -> proto.TokenMint_pb2.HederaTokenMintTransactionBody: ...
    @property
    def tokenBurn(self) -> proto.TokenBurn_pb2.HederaTokenBurnTransactionBody: ...
    def __init__(
        self,
        *,
        transactionID: proto.BasicTypes_pb2.HederaTransactionID | None = ...,
        transactionFee: builtins.int = ...,
        memo: builtins.str = ...,
        cryptoCreateAccount: proto.CryptoCreate_pb2.HederaCryptoCreateTransactionBody | None = ...,
        cryptoTransfer: proto.Transfer_pb2.HederaCryptoTransferTransactionBody | None = ...,
        tokenAssociate: proto.TokenAssociate_pb2.HederaTokenAssociateTransactionBody | None = ...,
        tokenMint: proto.TokenMint_pb2.HederaTokenMintTransactionBody | None = ...,
        tokenBurn: proto.TokenBurn_pb2.HederaTokenBurnTransactionBody | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["cryptoCreateAccount", b"cryptoCreateAccount", "cryptoTransfer", b"cryptoTransfer", "data", b"data", "tokenAssociate", b"tokenAssociate", "tokenBurn", b"tokenBurn", "tokenMint", b"tokenMint", "transactionID", b"transactionID"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["cryptoCreateAccount", b"cryptoCreateAccount", "cryptoTransfer", b"cryptoTransfer", "data", b"data", "memo", b"memo", "tokenAssociate", b"tokenAssociate", "tokenBurn", b"tokenBurn", "tokenMint", b"tokenMint", "transactionFee", b"transactionFee", "transactionID", b"transactionID"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["data", b"data"]) -> typing_extensions.Literal["cryptoCreateAccount", "cryptoTransfer", "tokenAssociate", "tokenMint", "tokenBurn"] | None: ...

global___HederaTransactionBody = HederaTransactionBody
