/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.5 */

#include "proto/wrappers.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(Hedera_DoubleValue, Hedera_DoubleValue, AUTO)


PB_BIND(Hedera_FloatValue, Hedera_FloatValue, AUTO)


PB_BIND(Hedera_Int64Value, Hedera_Int64Value, AUTO)


PB_BIND(Hedera_UInt64Value, Hedera_UInt64Value, AUTO)


PB_BIND(Hedera_Int32Value, Hedera_Int32Value, AUTO)


PB_BIND(Hedera_UInt32Value, Hedera_UInt32Value, AUTO)


PB_BIND(Hedera_BoolValue, Hedera_BoolValue, AUTO)


PB_BIND(Hedera_StringValue, Hedera_StringValue, AUTO)



#ifndef PB_CONVERT_DOUBLE_FLOAT
/* On some platforms (such as AVR), double is really float.
 * To be able to encode/decode double on these platforms, you need.
 * to define PB_CONVERT_DOUBLE_FLOAT in pb.h or compiler command line.
 */
PB_STATIC_ASSERT(sizeof(double) == 8, DOUBLE_MUST_BE_8_BYTES)
#endif

